[package]
name = "karlsen-wrpc-wasm"
description = "Karlsen wRPC WASM client"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
wasm32-sdk = ["karlsen-wrpc-client/wasm32-sdk"]
default = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
ahash.workspace = true
async-std.workspace = true
cfg-if.workspace = true
karlsen-addresses.workspace = true
karlsen-consensus-core.workspace = true
karlsen-consensus-client.workspace = true
karlsen-consensus-wasm.workspace = true
karlsen-notify.workspace = true
karlsen-wrpc-client.workspace = true
karlsen-rpc-core.workspace = true
karlsen-rpc-macros.workspace = true
karlsen-wasm-core.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
serde.workspace = true
workflow-log.workspace = true
workflow-rpc.workspace = true
workflow-wasm.workspace = true
wasm-bindgen.workspace = true
js-sys.workspace = true
wasm-bindgen-futures.workspace = true
workflow-core.workspace = true
futures.workspace = true

[lints]
workspace = true
