#!/bin/bash
set -e

# Workaround for Rust 1.87.0
# https://github.com/rust-lang/rust/issues/141048
export RUSTFLAGS=-Ctarget-cpu=mvp

wasm-pack build --weak-refs --target nodejs --out-name karlsen --out-dir nodejs/karlsen --features wasm32-sdk
